INSERT INTO SUBSCRIPTION_PLAN (PRICE, DURATION, SUBSCRIPTION_TYPE) VALUES (30, 'MONTH', 'BASIC');
INSERT INTO SUBSCRIPTION_PLAN (PRICE, DURATION, SUBSCRIPTION_TYPE) VALUES (60, 'MONTH', 'STANDARD');
INSERT INTO SUBSCRIPTION_PLAN (PRICE, DURATION, SUBSCRIPTION_TYPE) VALUES (90, 'MONTH', 'PREMIUM');
INSERT INTO SUBSCRIPTION_PLAN (PRICE, DURATION, SUBSCRIPTION_TYPE) VALUES (120, 'YEAR', 'BASIC');
INSERT INTO SUBSCRIPTION_PLAN (PRICE, DURATION, SUBSCRIPTION_TYPE) VALUES (150, 'YEAR', 'STANDARD');
INSERT INTO SUBSCRIPTION_PLAN (PRICE, DURATION, SUBSCRIPTION_TYPE) VALUES (180, 'YEAR', 'PREMIUM');